// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: proto/gasfee.proto

package gasfee

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GasFeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerToken string                 `protobuf:"bytes,1,opt,name=consumer_token,json=consumerToken,proto3" json:"consumer_token,omitempty"`
	ChainId       uint64                 `protobuf:"varint,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GasFeeRequest) Reset() {
	*x = GasFeeRequest{}
	mi := &file_proto_gasfee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GasFeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GasFeeRequest) ProtoMessage() {}

func (x *GasFeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gasfee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GasFeeRequest.ProtoReflect.Descriptor instead.
func (*GasFeeRequest) Descriptor() ([]byte, []int) {
	return file_proto_gasfee_proto_rawDescGZIP(), []int{0}
}

func (x *GasFeeRequest) GetConsumerToken() string {
	if x != nil {
		return x.ConsumerToken
	}
	return ""
}

func (x *GasFeeRequest) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

type GasFeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReturnCode    uint64                 `protobuf:"varint,1,opt,name=return_code,json=returnCode,proto3" json:"return_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	BlockFee      uint64                 `protobuf:"varint,3,opt,name=block_fee,json=blockFee,proto3" json:"block_fee,omitempty"`
	GasFee        uint64                 `protobuf:"varint,4,opt,name=gas_fee,json=gasFee,proto3" json:"gas_fee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GasFeeResponse) Reset() {
	*x = GasFeeResponse{}
	mi := &file_proto_gasfee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GasFeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GasFeeResponse) ProtoMessage() {}

func (x *GasFeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gasfee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GasFeeResponse.ProtoReflect.Descriptor instead.
func (*GasFeeResponse) Descriptor() ([]byte, []int) {
	return file_proto_gasfee_proto_rawDescGZIP(), []int{1}
}

func (x *GasFeeResponse) GetReturnCode() uint64 {
	if x != nil {
		return x.ReturnCode
	}
	return 0
}

func (x *GasFeeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GasFeeResponse) GetBlockFee() uint64 {
	if x != nil {
		return x.BlockFee
	}
	return 0
}

func (x *GasFeeResponse) GetGasFee() uint64 {
	if x != nil {
		return x.GasFee
	}
	return 0
}

var File_proto_gasfee_proto protoreflect.FileDescriptor

const file_proto_gasfee_proto_rawDesc = "" +
	"\n" +
	"\x12proto/gasfee.proto\x12\x0ecpchain.gasfee\"Q\n" +
	"\rGasFeeRequest\x12%\n" +
	"\x0econsumer_token\x18\x01 \x01(\tR\rconsumerToken\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\x04R\achainId\"\x81\x01\n" +
	"\x0eGasFeeResponse\x12\x1f\n" +
	"\vreturn_code\x18\x01 \x01(\x04R\n" +
	"returnCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tblock_fee\x18\x03 \x01(\x04R\bblockFee\x12\x17\n" +
	"\agas_fee\x18\x04 \x01(\x04R\x06gasFee2g\n" +
	"\x0eGasFeeServices\x12U\n" +
	"\x12getGasFeeByChainId\x12\x1d.cpchain.gasfee.GasFeeRequest\x1a\x1e.cpchain.gasfee.GasFeeResponse\"\x00B$\n" +
	"\x12com.cpchain.gasfeeZ\x0e./proto/gasfeeb\x06proto3"

var (
	file_proto_gasfee_proto_rawDescOnce sync.Once
	file_proto_gasfee_proto_rawDescData []byte
)

func file_proto_gasfee_proto_rawDescGZIP() []byte {
	file_proto_gasfee_proto_rawDescOnce.Do(func() {
		file_proto_gasfee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gasfee_proto_rawDesc), len(file_proto_gasfee_proto_rawDesc)))
	})
	return file_proto_gasfee_proto_rawDescData
}

var file_proto_gasfee_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_gasfee_proto_goTypes = []any{
	(*GasFeeRequest)(nil),  // 0: cpchain.gasfee.GasFeeRequest
	(*GasFeeResponse)(nil), // 1: cpchain.gasfee.GasFeeResponse
}
var file_proto_gasfee_proto_depIdxs = []int32{
	0, // 0: cpchain.gasfee.GasFeeServices.getGasFeeByChainId:input_type -> cpchain.gasfee.GasFeeRequest
	1, // 1: cpchain.gasfee.GasFeeServices.getGasFeeByChainId:output_type -> cpchain.gasfee.GasFeeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_gasfee_proto_init() }
func file_proto_gasfee_proto_init() {
	if File_proto_gasfee_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gasfee_proto_rawDesc), len(file_proto_gasfee_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gasfee_proto_goTypes,
		DependencyIndexes: file_proto_gasfee_proto_depIdxs,
		MessageInfos:      file_proto_gasfee_proto_msgTypes,
	}.Build()
	File_proto_gasfee_proto = out.File
	file_proto_gasfee_proto_goTypes = nil
	file_proto_gasfee_proto_depIdxs = nil
}
