// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: proto/gasfee.proto

package gasfee

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TokenGasPriceServices_GetTokenPriceAndGasByChainId_FullMethodName = "/cpchain.gasfee.TokenGasPriceServices/getTokenPriceAndGasByChainId"
)

// TokenGasPriceServicesClient is the client API for TokenGasPriceServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TokenGasPriceServicesClient interface {
	GetTokenPriceAndGasByChainId(ctx context.Context, in *TokenGasPriceRequest, opts ...grpc.CallOption) (*TokenGasPriceResponse, error)
}

type tokenGasPriceServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenGasPriceServicesClient(cc grpc.ClientConnInterface) TokenGasPriceServicesClient {
	return &tokenGasPriceServicesClient{cc}
}

func (c *tokenGasPriceServicesClient) GetTokenPriceAndGasByChainId(ctx context.Context, in *TokenGasPriceRequest, opts ...grpc.CallOption) (*TokenGasPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenGasPriceResponse)
	err := c.cc.Invoke(ctx, TokenGasPriceServices_GetTokenPriceAndGasByChainId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenGasPriceServicesServer is the server API for TokenGasPriceServices service.
// All implementations should embed UnimplementedTokenGasPriceServicesServer
// for forward compatibility.
type TokenGasPriceServicesServer interface {
	GetTokenPriceAndGasByChainId(context.Context, *TokenGasPriceRequest) (*TokenGasPriceResponse, error)
}

// UnimplementedTokenGasPriceServicesServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTokenGasPriceServicesServer struct{}

func (UnimplementedTokenGasPriceServicesServer) GetTokenPriceAndGasByChainId(context.Context, *TokenGasPriceRequest) (*TokenGasPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTokenPriceAndGasByChainId not implemented")
}
func (UnimplementedTokenGasPriceServicesServer) testEmbeddedByValue() {}

// UnsafeTokenGasPriceServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenGasPriceServicesServer will
// result in compilation errors.
type UnsafeTokenGasPriceServicesServer interface {
	mustEmbedUnimplementedTokenGasPriceServicesServer()
}

func RegisterTokenGasPriceServicesServer(s grpc.ServiceRegistrar, srv TokenGasPriceServicesServer) {
	// If the following call pancis, it indicates UnimplementedTokenGasPriceServicesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TokenGasPriceServices_ServiceDesc, srv)
}

func _TokenGasPriceServices_GetTokenPriceAndGasByChainId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenGasPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenGasPriceServicesServer).GetTokenPriceAndGasByChainId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenGasPriceServices_GetTokenPriceAndGasByChainId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenGasPriceServicesServer).GetTokenPriceAndGasByChainId(ctx, req.(*TokenGasPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TokenGasPriceServices_ServiceDesc is the grpc.ServiceDesc for TokenGasPriceServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenGasPriceServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cpchain.gasfee.TokenGasPriceServices",
	HandlerType: (*TokenGasPriceServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getTokenPriceAndGasByChainId",
			Handler:    _TokenGasPriceServices_GetTokenPriceAndGasByChainId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/gasfee.proto",
}
